POST http://localhost:80/api/publicUsers
Content-Type: application/json

{
    "userID": "juliusdittrich",
    "firstName": "julius",
    "lastName": "dittrich",
    "password": "password",
    "isAdministrator": "false"
}
###
POST http://localhost:80/api/publicUsers
Content-Type: application/json

{
    "userID": "marlowmix",
    "firstName": "marlow",
    "lastName": "mix",
    "password": "password",
    "isAdministrator": "false"
}
###
GET http://localhost:80/api/publicUsers
Content-Type: application/json

###
GET http://localhost:80/api/publicUsers/juliusdittrich
Content-Type: application/json

###
DELETE http://localhost:80/api/publicUsers/marlowmix
Content-Type: application/json

###
DELETE http://localhost:80/api/publicUsers/juliusdittrich
Content-Type: application/json

###
PUT http://localhost:80/api/publicUsers/juliusdittrich
Content-Type: application/json

{   
    "userID": "marlow",
    "isAdministrator": "true",
    "blabla": "sdg"
}

