// Login mit Basic Authentication mit korrekten Credentials admin:123
###
# @name loginAdminCorrect
GET http://localhost/api/authenticate
Authorization: Basic YWRtaW46MTIz

@adminToken = {{loginAdminCorrect.response.headers.Authorization}}

// Login mit Basic Authentication für manfred
###
# @name loginManfredCorrect
GET http://localhost/api/authenticate
Authorization: Basic manfred:asdf

@manfredToken = {{loginManfredCorrect.response.headers.Authorization}}

PUT http://localhost/localhost/api/degreeCourses/susi
Authorization: {{manfredToken}}
Content-Type: application/json
{
    
}



